services:
  web:
    image: php:8.1.1-apache
    container_name: lamp_web
    ports:
      - "80:80"
    volumes:
      - ./public_html:/var/www/html
      - ./php:/var/www/php
      - ./conf:/etc/apache2/sites-enabled
    environment:
      PHP_ERROR_REPORTING: "E_ALL & ~E_WARNING & ~E_NOTICE"
      PHP_DISPLAY_ERRORS: "Off"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: lamp_db
    environment:
      MYSQL_ROOT_PASSWORD: root@password
      MYSQL_DATABASE: weather_app
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql@password
    ports:
      - "3301:3301"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root@password
    ports:
      - "8080:80"
    depends_on:
      - db